SELECT * FROM customer;
SELECT (first_name, last_name) AS full_name FROM customer;
SELECT DISTINCT create_date FROM customer;
SELECT * FROM customer ORDER BY first_name DESC;
SELECT film_id, title, description, release_year, rental_rate FROM film ORDER BY rental_rate ASC;
SELECT address, phone FROM address WHERE district = 'Texas';
SELECT * FROM film WHERE film_id = 15 OR film_id = 150;
SELECT film_id, title, description, length, rental_rate FROM film WHERE title = 'Titanic';
SELECT film_id, title, description, length, rental_rate FROM film WHERE title LIKE 'Ti%';
SELECT * FROM film ORDER BY rental_rate ASC LIMIT 10;
SELECT * FROM film ORDER BY rental_rate ASC LIMIT 10 OFFSET 10;
SELECT * FROM film ORDER BY rental_rate ASC OFFSET 10 ROWS FETCH NEXT 10 ROWS ONLY;
SELECT customer.first_name, customer.last_name, payment.amount, payment.payment_date FROM customer INNER JOIN payment ON customer.customer_id = payment.customer_id;
SELECT * FROM film LEFT OUTER JOIN inventory ON film.film_id = inventory.film_id WHERE inventory.film_id IS NULL;
SELECT city.city, country.country FROM city INNER JOIN country ON city.country_id = country.country_id;
SELECT customer.customer_id, (staff.first_name, staff.last_name) AS fullname, staff.staff_id, payment.customer_id, payment.staff_id, payment.amount  FROM customer INNER JOIN payment ON customer.customer_id = payment.customer_id INNER JOIN staff ON staff.staff_id = payment.staff_id ORDER BY staff.staff_id ASC;
SELECT * FROM staff;